T140 parser
pax2pay/settlement-parser pull request #3
Opened 2023-12-27 19:57 UTC by AntonCroner

2023-12-28 09:44 UTC, marcushanses requested changes

2023-12-28 09:44 UTC, marcushanses commented on Input.ts
> +	readWhile(predicate: (me: Input) => boolean): Input {
why do you call it me?

2023-12-28 09:44 UTC, marcushanses commented on index.spec.ts
> +		expect(parser.mastercard.T140.parse("aaa")).toEqual(undefined)
This test is random and unnecessary.

2023-12-28 09:44 UTC, marcushanses commented on mastercard/T140/Page/Acknowledgement.ts
> +						member: data.header.member!,
How do you know? There is no check in this scope. Either make run and date optional or do the check.

2023-12-28 09:44 UTC, marcushanses commented on mastercard/T140/Page/Body.ts
> +export namespace Body {}
Remove or use the namespace.

2023-12-28 09:44 UTC, marcushanses commented on mastercard/T140/Page/Header.ts
> +			.filter(v => v && Object.keys(v).length > 0)
Looks very hacky and hard to edit if it is ever needed. You don't have to improve it but it would be nice.

2023-12-28 09:44 UTC, marcushanses commented on mastercard/T140/Page/NotificationFile.ts
> +					cycle: data.header.cycle!,
Don't do use non-null-assertions without checking if the value exists. This function can be used with input `data: Raw` and getting something that is not `NotificationFile | undefined` returned.

2023-12-28 09:44 UTC, marcushanses commented on mastercard/T140/Page/NotificationSummary.ts
> +					date: data.header.date!,
Please stop over using non-null-assertions...

2023-12-28 09:44 UTC, marcushanses commented on mastercard/T140/Page/Table.ts
> +				.trimEnd()
Use trim() instead of trimStart() and trimEnd().

2023-12-28 09:50 UTC, AntonCroner commented on mastercard/T140/Page/Table.ts
> +				.trimEnd()
\+

2023-12-28 12:42 UTC, AntonCroner commented on mastercard/T140/Page/Body.ts
> +export namespace Body {}
\+

2023-12-28 12:43 UTC, AntonCroner commented on mastercard/T140/Page/NotificationFile.ts
> +					cycle: data.header.cycle!,
\+

2023-12-29 08:56 UTC, marcushanses approved these changes

2023-12-29 10:03 UTC, merged